
AWS_REGION = 'us-west-2'


AWS_SNS_IOS_APP_ARN = 'arn:aws:sns:us-west-2:878165105740:app/APNS_SANDBOX/CarlorTest'
AWS_ACCESS_KEY_ID = 'AKIAJNDFKACQ6253GVXQ'
AWS_ACCESS_KEY = 'uOvbYfrPeE3hkNIHy9PZrPVNq445nmdPQkl6f33h'

MEMCACHE_ADDRESS = '127.0.0.1'



USER_APNS_SNS_TABLE = 'User_APNs_SNS_Table'
USER_TABLE = 'User_Table'
USER_TOPIC_TABLE = 'User_Topic_Table'
ACTIVATE_TABLE = 'User_Activate_Table'

COOKIE_SECRET = '_&xC#!~-2987UYWq|{RClubCIL}o><?[]axWERFC@'

ACTIVATOR_EMAILADDRESS = "billzeng808@gmail.com"